### ISSUE TITLE
Veryl panicks on build

### ISSUE THREAD

**Issue by nblei** [veryl-lang/veryl#589]
Building the following module

```veryl
/// A Saturating counter
module sat_counter #(
    param WIDTH      : u32          = 8 ,
    param RESET_VALUE: logic<WIDTH> = '0,
) (
    /// Clock
    i_clk: input logic,
    /// Reset
    i_rst: input logic,
    /// Enable Flag.  1 to enable incrementing/decrementing
    i_en: input logic,
    /// Direction Flag.  1 for up, 0 for down.
    i_direction: input logic,
    /// Value of counter
    o_val: output logic<WIDTH>,
    /// Next cycle's Value of counter
    o_val_next: output logic<WIDTH>,
    /// Flag indicating that the counter is saturated at its max value
    o_sat_max: output logic,
    /// Flag indicating that the counter is saturated at its min value
    o_sat_min: output logic,
    /// Flag indicating that the next counter is saturated at its max value
    o_sat_max_next: output logic,
    /// Flag indicating that the next counter is saturated at its min value
    o_sat_min_next: output logic,
) {

    assign o_sat_max = &o_val;
    assign o_sat_min = ~|o_val;

    assign o_val_next = if i_en {
        if i_direction { // 1 indicates count up
            if o_sat_max {
                o_val
            } else {
                o_val + 1
            }
        } else {
            if o_sat_min {
                o_val
            } else {
                o_val - 1
            }
        }
    } else {
        o_val
    };

    always_ff (i_clk, i_rst) {
        if_reset {
            o_val = RESET_VALUE;
        } else {
            o_val = o_val_next;
        }
    }

}
```
results in 

```
[INFO ]   Processing file (src/utils/sat_counter.veryl)
thread 'main' panicked at crates/analyzer/src/handlers/check_assignment.rs:55:51:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x55b883441556 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55b883441556 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b883441556 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55b883441556 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55b88346e1a0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55b88346e1a0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55b88343e35f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55b883441334 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55b883441334 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55b883442897 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55b8834425f9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55b883442d28 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55b883442bc9 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  13:     0x55b883441a56 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55b883442960 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55b882054605 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55b8820546c3 - core::panicking::panic::hb837a5ebbbe5b188
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
  17:     0x55b8826e3cb0 - core::option::Option<T>::unwrap::h1b13abe8c339a038
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:931:21
  18:     0x55b882763182 - <veryl_analyzer::handlers::check_assignment::CheckAssignment as veryl_parser::generated::veryl_grammar_trait::VerylGrammarTrait>::else::hdca7fc625fcb3f34
                               at /home/nathan/projects/veryl/crates/analyzer/src/handlers/check_assignment.rs:55:18
  19:     0x55b88213a512 - veryl_parser::veryl_walker::VerylWalker::else::h3acdd7dc53a1153c
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:389:9
  20:     0x55b8820f66f6 - veryl_parser::veryl_walker::VerylWalker::if_expression::h4e83a0e7f1f4aca9
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:1116:9
  21:     0x55b88214b3bf - veryl_parser::veryl_walker::VerylWalker::factor::hcd8517bb4f01f64d
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:1021:17
  22:     0x55b8820edc3a - veryl_parser::veryl_walker::VerylWalker::expression12::hd183823b178cd930
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:995:9
  23:     0x55b8820ed05b - veryl_parser::veryl_walker::VerylWalker::expression11::hed9e1f0ba48e275d
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:975:9
  24:     0x55b8820ec06b - veryl_parser::veryl_walker::VerylWalker::expression10::h0a0d2aa86f9c7aa8
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:964:9
  25:     0x55b8820eb517 - veryl_parser::veryl_walker::VerylWalker::expression09::h0363a712b56cd14f
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:950:9
  26:     0x55b8820eaa6b - veryl_parser::veryl_walker::VerylWalker::expression08::h210d1d857e08befd
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:939:9
  27:     0x55b8820ea51b - veryl_parser::veryl_walker::VerylWalker::expression07::hcdfcb2ec3a868a38
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:928:9
  28:     0x55b8820e9a7b - veryl_parser::veryl_walker::VerylWalker::expression06::h90ec9e98befe91f0
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:917:9
  29:     0x55b8820e8fdb - veryl_parser::veryl_walker::VerylWalker::expression05::h49e469dc9179d2aa
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:906:9
  30:     0x55b8820e853b - veryl_parser::veryl_walker::VerylWalker::expression04::h96fd2ac8c6299b8d
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:895:9
  31:     0x55b8820e7a9b - veryl_parser::veryl_walker::VerylWalker::expression03::he64acd5647e8e7ea
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:884:9
  32:     0x55b8820e6aab - veryl_parser::veryl_walker::VerylWalker::expression02::h31f5d24c76895695
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:873:9
  33:     0x55b8820e655b - veryl_parser::veryl_walker::VerylWalker::expression01::hfb26ecdd23efb9a5
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:862:9
  34:     0x55b8820d6abb - veryl_parser::veryl_walker::VerylWalker::expression::he42ec58d2de95442
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:851:9
  35:     0x55b8820f665a - veryl_parser::veryl_walker::VerylWalker::if_expression::h4e83a0e7f1f4aca9
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:1106:9
  36:     0x55b88214b3bf - veryl_parser::veryl_walker::VerylWalker::factor::hcd8517bb4f01f64d
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:1021:17
  37:     0x55b8820edc3a - veryl_parser::veryl_walker::VerylWalker::expression12::hd183823b178cd930
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:995:9
  38:     0x55b8820ed05b - veryl_parser::veryl_walker::VerylWalker::expression11::hed9e1f0ba48e275d
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:975:9
  39:     0x55b8820ec06b - veryl_parser::veryl_walker::VerylWalker::expression10::h0a0d2aa86f9c7aa8
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:964:9
  40:     0x55b8820eb517 - veryl_parser::veryl_walker::VerylWalker::expression09::h0363a712b56cd14f
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:950:9
  41:     0x55b8820eaa6b - veryl_parser::veryl_walker::VerylWalker::expression08::h210d1d857e08befd
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:939:9
  42:     0x55b8820ea51b - veryl_parser::veryl_walker::VerylWalker::expression07::hcdfcb2ec3a868a38
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:928:9
  43:     0x55b8820e9a7b - veryl_parser::veryl_walker::VerylWalker::expression06::h90ec9e98befe91f0
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:917:9
  44:     0x55b8820e8fdb - veryl_parser::veryl_walker::VerylWalker::expression05::h49e469dc9179d2aa
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:906:9
  45:     0x55b8820e853b - veryl_parser::veryl_walker::VerylWalker::expression04::h96fd2ac8c6299b8d
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:895:9
  46:     0x55b8820e7a9b - veryl_parser::veryl_walker::VerylWalker::expression03::he64acd5647e8e7ea
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:884:9
  47:     0x55b8820e6aab - veryl_parser::veryl_walker::VerylWalker::expression02::h31f5d24c76895695
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:873:9
  48:     0x55b8820e655b - veryl_parser::veryl_walker::VerylWalker::expression01::hfb26ecdd23efb9a5
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:862:9
  49:     0x55b8820d6abb - veryl_parser::veryl_walker::VerylWalker::expression::he42ec58d2de95442
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:851:9
  50:     0x55b882111339 - veryl_parser::veryl_walker::VerylWalker::assign_declaration::hc28056e965f9ae80
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:1685:9
  51:     0x55b8820e3d0c - veryl_parser::veryl_walker::VerylWalker::module_item::h43202a2fae94a1b0
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:2338:49
  52:     0x55b8820f0dcb - veryl_parser::veryl_walker::VerylWalker::module_group::hc2948ae33306eb88
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:2318:48
  53:     0x55b882115b37 - veryl_parser::veryl_walker::VerylWalker::module_declaration::h54d8fd9e48dbc1fa
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:2235:13
  54:     0x55b882108a71 - veryl_parser::veryl_walker::VerylWalker::description_item::hca736e616beaa4ef
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:2578:54
  55:     0x55b88210c1cb - veryl_parser::veryl_walker::VerylWalker::description_group::h40a6435cc7ce6011
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:2569:58
  56:     0x55b882147521 - veryl_parser::veryl_walker::VerylWalker::veryl::h8265ff1e54083a8e
                               at /home/nathan/projects/veryl/crates/parser/src/veryl_walker.rs:2595:13
  57:     0x55b882165fb5 - veryl_analyzer::analyzer::Analyzer::analyze_pass2::ha0c032790df6a031
                               at /home/nathan/projects/veryl/crates/analyzer/src/analyzer.rs:100:9
  58:     0x55b8821792e4 - veryl::cmd_build::CmdBuild::exec::h62415a923c0c8b2d
                               at /home/nathan/projects/veryl/crates/veryl/src/cmd_build.rs:49:30
  59:     0x55b8820727c1 - veryl::main::hdb537e414548a9f4
                               at /home/nathan/projects/veryl/crates/veryl/src/main.rs:243:31
  60:     0x55b88209ffd2 - core::ops::function::FnOnce::call_once::h8bde5dec66239d51
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  61:     0x55b8820b2da5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h962aad157ebe2f07
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  62:     0x55b882071966 - std::rt::lang_start::{{closure}}::h3c81f348fce59bc2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  63:     0x55b883436f51 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  64:     0x55b883436f51 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  65:     0x55b883436f51 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  66:     0x55b883436f51 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  67:     0x55b883436f51 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  68:     0x55b883436f51 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  69:     0x55b883436f51 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  70:     0x55b883436f51 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  71:     0x55b883436f51 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  72:     0x55b88207193a - std::rt::lang_start::h52725e42157e0b74
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  73:     0x55b88207a97e - main
  74:     0x7f916d029d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  75:     0x7f916d029e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  76:     0x55b882054ee5 - _start
  77:                0x0 - <unknown>
```

**Comment by dalance** [comment]
Thanks!
I've fixed it.
